/*
 * Copyright (c) 2023 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.oceanbase.tools.datamocker.model.mock;

import com.oceanbase.tools.datamocker.datatype.AbstractDataType;
import com.oceanbase.tools.datamocker.util.Pair;
import lombok.Getter;
import org.apache.commons.lang.Validate;

/**
 * A simple JavaBean used to encapsulate the data generated on each column of the simulated data
 *
 * @author yh263208
 * @date 2021-02-22 11:44
 * @since OBMOCKER_snapshit_0.1.0
 */
public class MockColumnData<T> {
    /**
     * A data column contains two parts of information, one part is the type of the column, and the
     * other part is the data generated by the column
     */
    private final Pair<AbstractDataType<T, ? extends Comparable<?>>, T> column;
    /**
     * Name of a column
     */
    @Getter
    private final String columnName;

    /**
     * Default Constructor for MockColumn
     *
     * @param columnName Name for a column
     * @param dataType data type for a column
     * @param columnValue value for a column
     * @exception IllegalArgumentException columnName and datatype can not be null
     */
    public MockColumnData(String columnName, AbstractDataType<T, ? extends Comparable<?>> dataType, T columnValue) {
        Validate.notEmpty(columnName, "ColumnName can not be blank for MockColumn");
        Validate.notNull(dataType, "DataType can not be null for MockColumn");
        this.column = new Pair<>(dataType, columnValue);
        this.columnName = columnName;
    }

    /**
     * Get column Value
     *
     * @return column value
     */
    public T getColumnValue() {
        return this.column.getValue();
    }

    /**
     * Get object for jdbc operation
     *
     * @return jdbc object
     */
    public Object getJdbcColumnValue() {
        return this.column.getKey().convertFromJavaObjectToJdbcObject(getColumnValue());
    }

    /**
     * Get Column Value string
     *
     * @return column value string
     */
    public String getColumnValueString() {
        return this.column.getKey().convertToSqlString(getColumnValue());
    }

    /**
     * Get Column Data type
     *
     * @return Column DataType
     */
    public AbstractDataType<T, ? extends Comparable<?>> getColumnDataType() {
        return this.column.getKey();
    }

    /**
     * To digest object
     *
     * @return digest object
     */
    public T toDigest() {
        AbstractDataType<T, ? extends Comparable<?>> dataType = getColumnDataType();
        return dataType.toDigest(dataType.convertFromJdbcObjectToJavaObject(getColumnValue()));
    }

    /**
     * To digest string
     *
     * @return digest string
     */
    public String toDisgestString() {
        return getColumnDataType().convertToSqlString(toDigest());
    }
}
