/*
 * Copyright (c) 2023 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.oceanbase.tools.datamocker.model.mock;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import lombok.NonNull;
import org.apache.commons.lang.Validate;

/**
 * One row of data, including one row of data generated by simulation data, containing multiple
 * columns
 *
 * @author yh263208
 * @date 2021-02-22 11:50
 * @since OBMOCKER_snapshot_0.1.0
 */
public class MockRowData {

    private final Map<String, MockColumnData<?>> rowWithMultiColumn;

    public MockRowData(@NonNull List<MockColumnData<?>> columnList) {
        this.rowWithMultiColumn = new HashMap<>(columnList.size());
        for (MockColumnData<?> columnItem : columnList) {
            rowWithMultiColumn.put(columnItem.getColumnName(), columnItem);
        }
    }

    public MockRowData() {
        this.rowWithMultiColumn = new HashMap<>();
    }

    public MockRowData(int rowWidth) {
        Validate.isTrue(rowWidth > 0, "Row width can not be negative for MockRowData");
        this.rowWithMultiColumn = new HashMap<>(rowWidth);
    }

    public MockColumnData<?> getMockColumn(@NonNull String columnName) {
        return this.rowWithMultiColumn.get(columnName);
    }

    public MockColumnData<?> remove(@NonNull MockColumnData<?> mockColumn) {
        return this.rowWithMultiColumn.remove(mockColumn.getColumnName());
    }

    public MockColumnData<?> remove(@NonNull String columnName) {
        return this.rowWithMultiColumn.remove(columnName);
    }

    public MockColumnData<?> addMockColumn(@NonNull MockColumnData<?> mockColumn) {
        return this.rowWithMultiColumn.putIfAbsent(mockColumn.getColumnName(), mockColumn);
    }

    public int columnNum() {
        synchronized (this.rowWithMultiColumn) {
            return this.rowWithMultiColumn.size();
        }
    }

    public Set<String> columnNames() {
        return this.rowWithMultiColumn.keySet();
    }

    public List<MockColumnData<?>> getMockColumns() {
        return new ArrayList<>(this.rowWithMultiColumn.values());
    }

}
