/*
 * Copyright (c) 2023 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.oceanbase.tools.datamocker.generator.digit;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.oceanbase.tools.datamocker.model.exception.MockerException;
import com.oceanbase.tools.datamocker.util.Range;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * Range Random Number Generator Test Object
 *
 * @author yh263208
 * @date 2020-12-11 22:01
 * @since OBMOCKER_snapshot_0.1.0
 */
public class RangeGeneratorTest {
    /**
     * Weight mapping table, used to characterize the weight generated by the data on each data segment
     */
    private final Map<Range<BigDecimal>, Double> weightMap = new HashMap<>();
    private final Range<BigDecimal> range1 = new Range<>(new BigDecimal("10"), new BigDecimal("14.12"));
    private final Range<BigDecimal> range2 = new Range<>(new BigDecimal("14.23"), new BigDecimal("16.345"));
    private final Range<BigDecimal> range3 = new Range<>(new BigDecimal("17.56"), new BigDecimal("19.45"));
    private final Range<BigDecimal> range4 = new Range<>(new BigDecimal("20.33"), new BigDecimal("25.33"));
    private final Range<BigDecimal> range5 = new Range<>(new BigDecimal("26.78"), new BigDecimal("27.25"));
    private final Range<BigDecimal> range6 = new Range<>(new BigDecimal("30.44"), new BigDecimal("35.55"));
    private final Range<BigDecimal> range7 = new Range<>(new BigDecimal("36.78"), new BigDecimal("50"));

    @Before
    public void initWeightMap() {
        weightMap.put(range1, 0.13);
        weightMap.put(range2, 0.23);
        weightMap.put(range3, 0.08);
        weightMap.put(range4, 0.16);
        weightMap.put(range5, 0.11);
        weightMap.put(range6, 0.16);
        weightMap.put(range7, 0.13);
    }

    @Test
    public void testRangeGenerator() {
        RangeGenerator generator = new RangeGenerator(this.weightMap);
        BigDecimal min = new BigDecimal("5");
        BigDecimal max = new BigDecimal("50");
        Map<Range<BigDecimal>, Integer> countMap = new HashMap<>();
        Set<Range<BigDecimal>> keySet = this.weightMap.keySet();
        Iterator<Range<BigDecimal>> iter = keySet.iterator();
        List<Range<BigDecimal>> list = new ArrayList<>();
        while (iter.hasNext()) {
            Range<BigDecimal> key = iter.next();
            list.add(key);
        }
        int totalCount = 10000;
        for (int i = 0; i < totalCount; i++) {
            BigDecimal value = generator.generate(min, max);
            boolean flag = false;
            for (Range<BigDecimal> item : list) {
                flag = item.contain(value);
                if (flag) {
                    Integer count = countMap.getOrDefault(item, 0);
                    countMap.put(item, count + 1);
                    break;
                }
            }
            Assert.assertTrue(flag);
        }
        keySet = weightMap.keySet();
        iter = keySet.iterator();
        while (iter.hasNext()) {
            Range<BigDecimal> key = iter.next();
            Double factor = weightMap.get(key);
            Double realFactor = countMap.get(key).doubleValue() / totalCount;
            double interval = Math.abs(factor - realFactor);
            Assert.assertTrue(interval < 0.05);
        }
    }

    @Test(expected = MockerException.class)
    public void testRangeGenertorWithErrorRatio() {
        weightMap.put(range1, 0.1);
        RangeGenerator generator = new RangeGenerator(this.weightMap);
    }

    @Test(expected = MockerException.class)
    public void testRangeGenertorWithOutOfBound() {
        weightMap.put(range3, 0.04);
        weightMap.put(new Range<>(new BigDecimal("10"), new BigDecimal("60")), 0.04);
        RangeGenerator generator = new RangeGenerator(this.weightMap);
        BigDecimal min = new BigDecimal("5");
        BigDecimal max = new BigDecimal("50");
        generator.preCheck(min, max);
        int totalCount = 10000;
        for (int i = 0; i < totalCount; i++) {
            generator.generate(min, max);
        }
    }

    @Test(expected = MockerException.class)
    public void testRangeGenertorWithOutOfMinBound() {
        weightMap.put(range3, 0.04);
        weightMap.put(new Range<>(new BigDecimal("2"), new BigDecimal("12")), 0.04);
        RangeGenerator generator = new RangeGenerator(this.weightMap);
        BigDecimal min = new BigDecimal("5");
        BigDecimal max = new BigDecimal("50");
        generator.preCheck(min, max);
        int totalCount = 10000;
        for (int i = 0; i < totalCount; i++) {
            generator.generate(min, max);
        }
    }
}
