package com.oceanbase.tools.datamocker.model.mock;

import com.oceanbase.tools.datamocker.datatype.AbstractDataType;
import com.oceanbase.tools.datamocker.util.Pair;

/**
 * A simple JavaBean used to encapsulate the data generated on each column of the simulated data
 *
 * @author yh263208
 * @date 2021-02-22 11:44
 * @since OBMOCKER_snapshit_0.1.0
 */
public class MockColumn {
    /**
     * A data column contains two parts of information, one part is the type of the column,
     * and the other part is the data generated by the column
     */
    private Pair<AbstractDataType, Object> column;
}
