package com.oceanbase.tools.datamocker.model.mock;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import com.oceanbase.tools.datamocker.model.exception.MockerError;
import com.oceanbase.tools.datamocker.model.exception.MockerException;
import org.apache.commons.lang.StringUtils;

/**
 * One row of data, including one row of data generated by simulation data,
 * containing multiple columns
 *
 * @author yh263208
 * @date 2021-02-22 11:50
 * @since OBMOCKER_snapshot_0.1.0
 */
public class MockRow {
    /**
     * A row of data, including multiple columns, is a key-value data structure,
     * the key is the column name of the column, and the value is the actual data of the column
     */
    private Map<String, MockColumn> row;

    public MockRow() {
        this.row = new HashMap<>();
    }

    /**
     * Get a column of data
     *
     * @param name Column name
     * @return Return column data
     */
    public MockColumn get(String name) {
        if (StringUtils.isBlank(name)) {
            throw new MockerException(MockerError.PARAMETER_ERROR, "Name for mock row can not be null or empty");
        }
        if (row == null) {
            throw new MockerException(MockerError.UNKNOWN_ERROR, "Mock row is null, unknown error");
        }
        return this.row.get(name);
    }

    /**
     * Set up a column of data
     *
     * @param columnName Corresponding column name
     * @param data       Corresponding data
     */
    public MockColumn putIfAbsent(String columnName, MockColumn data) {
        if (this.row == null) {
            throw new MockerException(MockerError.UNKNOWN_ERROR, "Mock row is null, unknown error");
        }
        return this.row.putIfAbsent(columnName, data);
    }

    /**
     * Get how many columns of data are contained in the current row
     *
     * @return Return size
     */
    public int size() {
        if (this.row == null) {
            throw new MockerException(MockerError.UNKNOWN_ERROR, "Mock row is null, unknown error");
        }
        return this.row.size();
    }

    /**
     * Get the column collection of row data
     *
     * @return Return column collection
     */
    public Set<String> columns() {
        if (this.row == null) {
            return null;
        }
        return this.row.keySet();
    }

}
