package com.oceanbase.tools.datamocker.datatype;

import java.security.NoSuchAlgorithmException;

import com.oceanbase.tools.datamocker.generator.BaseByteGenerator;
import com.oceanbase.tools.datamocker.model.enums.ObModeType;
import com.oceanbase.tools.datamocker.model.exception.MockerError;
import com.oceanbase.tools.datamocker.model.exception.MockerException;
import com.oceanbase.tools.datamocker.util.DigestUtil;

/**
 * Abstract byte data type
 *
 * @author yh263208
 * @date 2020-12-16 22:35
 * @since OBMOCKER_snapshot_0.1.0
 */
public abstract class AbstractByteDataType extends AbstractDataType<byte[], Integer> {
    /**
     * The constructor of the abstract base class, where you need to pass in the random data generator
     * bound to this data type, and specify the OB mode corresponding to the data type and the database
     * type in this mode
     *
     * @param generator Byte type data generator
     * @param dialectType OB dialect type
     * @param allowNull Whether to allow null values
     */
    public AbstractByteDataType(BaseByteGenerator generator, ObModeType dialectType, byte[] defaultValue,
            Boolean allowNull) {
        super(generator, dialectType, defaultValue, allowNull);
    }

    /**
     * The constructor of the abstract base class, where you need to pass in the random data generator
     * bound to this data type, and specify the OB mode corresponding to the data type and the database
     * type in this mode
     *
     * @param dialectType OB dialect type
     * @param defaultValue default value for byte data type
     * @param allowNull Whether to allow null values
     */
    protected AbstractByteDataType(ObModeType dialectType, byte[] defaultValue, Boolean allowNull) {
        super(dialectType, defaultValue, allowNull);
    }

    /**
     * The minimum byte length of the character type, the default is 1
     *
     * @return Return length
     */
    @Override
    protected Integer minValueForType() {
        return 1;
    }

    /**
     * The maximum amount of unique data that this type can generate under the constraints of the
     * specified data generator
     *
     * @return Return specific value
     */
    @Override
    public Long distinctLimit() {
        if (generator == null || generator.count(lowValue(), highValue()) == null) {
            return Long.MAX_VALUE;
        }
        return generator.count(lowValue(), highValue());
    }

    /**
     * Pre-check method, used to verify whether the data generated by the data generator is legal
     *
     * @param value Data to be inserted
     * @return Return the verified data
     * @throws MockerException An exception is thrown if verification fails
     */
    @Override
    protected byte[] preProcessingBeforeOutput(byte[] value) {
        if (value == null) {
            return null;
        }
        Integer maxLength = highValue();
        if (value.length > maxLength) {
            throw new MockerException(MockerError.VALUE_OUT_OFRANGE,
                    String.format("The length of then generator's value is bigger than bound [0,%d]", maxLength));
        }
        return value;
    }

    /**
     * Returns the data summary, the number type data summary is itself
     *
     * @param value original value
     * @return Back to summary
     */
    @Override
    public byte[] toDigest(byte[] value) {
        try {
            return DigestUtil.getToken(value);
        } catch (NoSuchAlgorithmException e) {
            throw new MockerException(MockerError.UNKNOWN_ERROR, e.getMessage());
        }
    }
}
