package com.oceanbase.tools.datamocker.schedule.impl;

import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import com.oceanbase.tools.datamocker.constraint.AbstractConstraint;
import com.oceanbase.tools.datamocker.core.read.ColumnReader;
import com.oceanbase.tools.datamocker.core.task.TableTaskContext;
import com.oceanbase.tools.datamocker.core.task.TableTaskMetaData;
import com.oceanbase.tools.datamocker.model.exception.MockerError;
import com.oceanbase.tools.datamocker.model.exception.MockerException;
import com.oceanbase.tools.datamocker.model.mock.MockColumnData;
import com.oceanbase.tools.datamocker.model.mock.MockRowData;
import com.oceanbase.tools.datamocker.schedule.AbstractMockTask;
import com.oceanbase.tools.datamocker.util.MockerBuffer;
import com.oceanbase.tools.datamocker.util.PrintUtil;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang.Validate;

/**
 * Mock data undertakes the task of actual data generation, and the main logic is to generate data
 * based on the generation primitives
 *
 * @author yh263208
 * @date 2021-01-14 11:17
 * @since OBMOCKER_snapshot_0.1.0
 */
@Slf4j
public class GenerateDataTask extends AbstractMockTask {
    /**
     * Buffer, used to store the data generated by the column generation task
     */
    private final MockerBuffer buffer;
    /**
     * Column generation primitive set
     */
    private final List<ColumnReader<?>> readers;
    /**
     * Column constraint set, through the set to determine whether the data generated by the column
     * generation primitive meets the constraint
     */
    private final List<AbstractConstraint> constraints = new LinkedList<>();

    public GenerateDataTask(TableTaskMetaData metaData, TableTaskContext context, MockerBuffer buffer,
            List<ColumnReader<?>> readers, List<AbstractConstraint> constraints) {
        super(metaData, context);
        Validate.notNull(buffer, "Buffer for GenerateDataTask can not be null");
        Validate.notNull(readers, "Column readers for GenerateDataTask can not be null");
        Validate.notNull(constraints, "Constraints for GenerateDataTask can not be null");
        this.buffer = buffer;
        this.readers = readers;
        for (AbstractConstraint constraint : constraints) {
            Set<String> colSet = constraint.columns().get(metaData.getTableName()).keySet();
            for (ColumnReader<?> reader : readers) {
                if (colSet.contains(reader.getColumnName())) {
                    this.constraints.add(constraint);
                    break;
                }
            }
        }
    }

    @Override
    public void execute(TableTaskMetaData metaData, TableTaskContext context) throws Exception {
        List<String> columnNames = this.readers.stream().map(ColumnReader::getColumnName).collect(Collectors.toList());
        List<String> constraintNames =
                this.constraints.stream().map(AbstractConstraint::name).collect(Collectors.toList());
        log.info("Start the data generation task, threadName={},constraintName={},columnName={}",
                Thread.currentThread().getName(),
                constraintNames, columnNames);
        long counter = 0;
        // Cyclic idling counter, usually if idling exceeds totalCount and has not written any data, it is
        // considered that the write is abnormal
        long emptyLoopCount = 0;
        Exception exception = null;
        long batchDataGenerateTime = 0;
        long batchDataLineUpTime = 0;
        long batchDataCheckTime = 0;
        try {
            while ((counter++) < metaData.getTotalCount() && !Thread.currentThread().isInterrupted()
                    && this.interval() <= metaData.getTimeoutMilliseconds()) {
                MockRowData mockRowData = new MockRowData(this.readers.size());
                long startNanoTime = System.nanoTime();
                for (ColumnReader<?> item : readers) {
                    MockColumnData<?> mockColumn = item.read();
                    mockRowData.addMockColumn(mockColumn);
                }
                batchDataGenerateTime += (System.nanoTime() - startNanoTime);
                boolean passCheck = true;
                emptyLoopCount++;
                startNanoTime = System.nanoTime();
                for (AbstractConstraint constraint : this.constraints) {
                    if (!constraint.check(mockRowData)) {
                        passCheck = false;
                        counter--;
                        break;
                    }
                }
                batchDataCheckTime += (System.nanoTime() - startNanoTime);
                if (passCheck) {
                    emptyLoopCount = 0L;
                    long writeTimeout = metaData.getTimeoutMilliseconds() - this.interval();
                    if (writeTimeout <= 0) {
                        writeTimeout = 2000;
                    }
                    startNanoTime = System.nanoTime();
                    buffer.write(mockRowData, writeTimeout, TimeUnit.MILLISECONDS);
                    batchDataLineUpTime += (System.nanoTime() - startNanoTime);
                    startNanoTime = System.nanoTime();
                    for (AbstractConstraint constraint : this.constraints) {
                        constraint.mark(mockRowData);
                    }
                    batchDataCheckTime += (System.nanoTime() - startNanoTime);
                }
                if (emptyLoopCount > metaData.getTotalCount() * 100 || emptyLoopCount > 1000000) {
                    throw new MockerException(MockerError.UNKNOWN_ERROR, String.format(
                            "Data generation cycle idling %d exceeds the maximum number of data generation %d, too much data cannot pass the constraint check, data generation is terminated",
                            emptyLoopCount, metaData.getTotalCount() * 100));
                }
                if (counter % metaData.getBatchSize() == 0 || counter == metaData.getTotalCount()) {
                    log.debug("Batch data generation completed, generateTime={}, checkTime={}, lineUpTime={}",
                            PrintUtil.convertToReadableTimeString(batchDataGenerateTime, TimeUnit.NANOSECONDS,
                                    TimeUnit.SECONDS, TimeUnit.MILLISECONDS),
                            PrintUtil.convertToReadableTimeString(batchDataCheckTime, TimeUnit.NANOSECONDS,
                                    TimeUnit.SECONDS, TimeUnit.MILLISECONDS),
                            PrintUtil.convertToReadableTimeString(batchDataLineUpTime, TimeUnit.NANOSECONDS,
                                    TimeUnit.SECONDS, TimeUnit.MILLISECONDS));
                    batchDataGenerateTime = 0;
                    batchDataLineUpTime = 0;
                    batchDataCheckTime = 0;
                }
            }
            counter--;
        } catch (Exception e) {
            exception = e;
            log.error("Data generation task execution failed", e);
        } finally {
            long writeTimeout = metaData.getTimeoutMilliseconds() - this.interval();
            if (writeTimeout < 0) {
                writeTimeout = 0;
            }
            buffer.close(writeTimeout, TimeUnit.MILLISECONDS);
        }
        if (exception != null) {
            throw exception;
        }
        if (Thread.currentThread().isInterrupted()) {
            log.warn("Data generation task execution is interrupted, totalDataGenerated={}, duration={} ms", counter,
                    interval());
            throw new InterruptedException("data mock business has been interrupted by user");
        }
        if (this.interval() >= metaData.getTimeoutMilliseconds()) {
            log.warn("Data generation task execution timed out, totalDataGenerated={}, duration={} ms", counter,
                    interval());
        }
        if (counter >= metaData.getTotalCount()) {
            log.info("Data generation task is executed successfully, totalDataGenerated={}, duration={} ms", counter,
                    interval());
        }
        context.appendDataGenInfo(counter);
    }

    /**
     * Set constraints
     *
     * @param constraints Constraint set
     */
    public void reloadConstraints(List<AbstractConstraint> constraints) {
        Validate.notNull(constraints, "Constraints can not be null for GenerateDataTask#setConstraints");
        int length = this.constraints.size();
        for (int i = 0; i < length; i++) {
            AbstractConstraint constraint = this.constraints.get(i);
            for (AbstractConstraint item : constraints) {
                if (item.name().equals(constraint.name())) {
                    this.constraints.set(i, item);
                }
            }
        }
    }

}
